server:
  port: 8088

spring:
  application:
    name: inventory-receipt
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MockProjectIntern/Config-repo.git
          clone-on-start: true